# syntax=docker/dockerfile:1

FROM gradle:8.5-jdk17-alpine as build-app

WORKDIR /app

COPY build.gradle ./
COPY settings.gradle ./
COPY ApiGateway ./ApiGateway

RUN gradle :apiGateway:build --no-daemon

FROM eclipse-temurin:17-jre-alpine

COPY --from=build-app /app/ApiGateway/build/libs/ApiGateway.jar /ApiGateway.jar

EXPOSE 8181

CMD ["java", "-jar","/ApiGateway.jar"]


