apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: k8s-program
  name: song-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  hostPath:
    path: "/mnt/d/Programming/projects/songs"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: k8s-program
  name: song-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 2Gi

---

apiVersion: v1
kind: Service
metadata:
  namespace: k8s-program
  name: song-db
  labels:
    app: song-db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      name: web
  selector:
    app: song-db

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: k8s-program
  name: song-db
spec:
  selector:
    matchLabels:
      app: song-db # has to match .spec.template.metadata.labels
  serviceName: "song-db"
  template:
    metadata:
      labels:
        app: song-db # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: song-db
          image: postgres:13.3-alpine
          env:
            - name: POSTGRES_DB
              value: "songs_db"
            - name: POSTGRES_USER
              value: "user"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          ports:
            - containerPort: 5432
              name: web
          volumeMounts:
            - name: www-persistent-storage
              mountPath: /var/lib/postgresql/data/pgdata
      volumes:
        - name: www-persistent-storage
          persistentVolumeClaim:
            claimName: song-claim
