apiVersion: v1
kind: ConfigMap
metadata:
  name: song-service-config-map
  namespace: k8s-program
data:
  SERVER_PORT: "8180"
  API_GATEWAY_URL: "http://${RESOURCE-SERVICE_SERVICE_HOST}:${RESOURCE-SERVICE_SERVICE_PORT}"
  SERVICE_REGISTRY_URL: "http://service-registry:8083/eureka"
  SONGS_DB_URL: "jdbc:postgresql://${SONG-DB_SERVICE_HOST}:5432/songs_db"
  
---

apiVersion: v1
kind: Service
metadata:
  namespace: k8s-program
  name: song-service
spec:
  type: NodePort
  selector:
    app: song-service-pod
  ports:
    - port: 8180
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 8180
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: k8s-program
  name: song-service-deployment
  labels:
    app: song-service-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: song-service-pod
  template:
    metadata:
      labels:
        app: song-service-pod
    spec:
      containers:
        - name: song-service-pod
          image: song-service:0.2
#          args:
#            - /bin/sh
#            - -c
#            - touch /home/health
          envFrom:
            - configMapRef:
                name: song-service-config-map
          env:
            - name: SONGS_DB_USR
              valueFrom:
                secretKeyRef:
                  name: song-secret
                  key: username
            - name: SONGS_DB_PWD
              valueFrom:
                secretKeyRef:
                  name: song-secret
                  key: password
          ports:
            - containerPort: 8180
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: www-persistent-storage
              mountPath: /home
          livenessProbe:
            exec:
              command:
                - cat
                - /home/health
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8180
            initialDelaySeconds: 3
            periodSeconds: 3
          startupProbe:
            httpGet:
              path: /started
              port: 8180
            initialDelaySeconds: 10
            periodSeconds: 3
      volumes:
        - name: www-persistent-storage
          persistentVolumeClaim:
            claimName: song-claim-test
