apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: k8s-program
  name: song-pv-test
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  hostPath:
#    path: "/mnt/d/Programming/projects/testVolume"
    path: "/mnt/c/k8s-program/test"
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: k8s-program
  name: song-claim-test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 2Gi
            
