apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: k8s-program
  name: song-pv-test
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  hostPath:
    path: "/mnt/d/Programming/projects/testVolume"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: k8s-program
  name: song-claim-test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 2Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: k8s-program
  name: song-service-deployment-test
  labels:
    app: song-service-app-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: song-service-pod-test
  template:
    metadata:
      labels:
        app: song-service-pod-test
    spec:
      containers:
        - name: song-service-pod-test
          image: song-service:latest
          env:
            - name: SERVER_PORT
              value: "8180"
            - name: API_GATEWAY_URL
              value: "http://${RESOURCE-SERVICE_SERVICE_HOST}:${RESOURCE-SERVICE_SERVICE_PORT}"
            - name: SERVICE_REGISTRY_URL
              value: "http://service-registry:8083/eureka"
            - name: SONGS_DB_URL
              value: "jdbc:postgresql://${SONG-DB_SERVICE_HOST}:5432/songs_db"
            - name: SONGS_DB_USR
              value: "user"
            - name: SONGS_DB_PWD
              value: "password"
          ports:
            - containerPort: 8180
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: www-persistent-storage
              mountPath: /home
      volumes:
        - name: www-persistent-storage
          persistentVolumeClaim:
            claimName: song-claim-test
            
