scrape_configs:
  - job_name: 'resources-service'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus' ##prometheus endpoint
    static_configs:
      - targets: ['resources-service:8181'] ## host and port for your mis