# syntax=docker/dockerfile:1

FROM gradle:8.5-jdk17-alpine as build-app

WORKDIR /app

COPY build.gradle ./
COPY settings.gradle ./
COPY src ./src

RUN gradle build --no-daemon

FROM eclipse-temurin:17-jre-alpine

COPY --from=build-app /app/build/libs/AuthServer.jar /AuthServer.jar

EXPOSE 9999

CMD ["java","-jar","/AuthServer.jar"]

