# syntax=docker/dockerfile:1

FROM eclipse-temurin:17-jdk-alpine

WORKDIR /app

COPY gradle ./gradle
COPY build.gradle ./
COPY gradlew ./
COPY gradlew.bat ./
COPY settings.gradle ./

COPY ServiceRegistry ./ServiceRegistry

EXPOSE 8083

ENTRYPOINT ["./gradlew", ":serviceRegistry:bootRun"]


