# syntax=docker/dockerfile:1

FROM gradle:8.5-jdk17-alpine as build-app

WORKDIR /app

COPY build.gradle ./
COPY settings.gradle ./
COPY ServiceRegistry ./ServiceRegistry

RUN gradle :serviceRegistry:build --no-daemon

FROM eclipse-temurin:17-jre-alpine

COPY --from=build-app /app/ServiceRegistry/build/libs/ServiceRegistry.jar /ServiceRegistry.jar

EXPOSE 8181

CMD ["java", "-jar","/ServiceRegistry.jar"]


